[mypy]
python_version = 3.14
strict = True
warn_unreachable = True
disallow_any_unimported = True
disallow_subclassing_any = True

[mypy-chromadb.*]
ignore_missing_imports = True

[mypy-gradio.*]
ignore_missing_imports = True

[mypy-sentence_transformers.*]
ignore_missing_imports = True

[mypy-ollama.*]
ignore_missing_imports = True
